name: Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Pylint source directories
        working-directory: src
        run: poetry run pylint $(git ls-files '*.py')

      - name: Lint with flake8
        working-directory: src
        run: poetry run flake8 .

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      
      - name: Helm add Prometheus
        run: |
          helm repo add prom-repo https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install myprom prom-repo/kube-prometheus-stack
